/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Lucas Oliveira
 */
public class PrimeiroAcesso extends javax.swing.JPanel {
    private JPanel container;

    /**
     * Creates new form PrimeiroAcesso
     * @param pn
     */
    public PrimeiroAcesso(JPanel pn) {
        this.container = pn;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JLabel();
        btnIrParaLogin = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1300, 700));
        setLayout(null);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botão Fechar.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        add(btnClose);
        btnClose.setBounds(1050, 150, 50, 50);

        btnIrParaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botão Próximo.png"))); // NOI18N
        btnIrParaLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIrParaLogin.setPreferredSize(new java.awt.Dimension(100, 40));
        btnIrParaLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIrParaLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIrParaLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIrParaLoginMouseExited(evt);
            }
        });
        add(btnIrParaLogin);
        btnIrParaLogin.setBounds(525, 500, 350, 65);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Primeiro Acesso.png"))); // NOI18N
        background.setFocusable(false);
        background.setName("Background"); // NOI18N
        add(background);
        background.setBounds(0, 0, 1300, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIrParaLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIrParaLoginMouseEntered
        toggleBtnImage(evt, "hover", "Botão Próximo");
    }//GEN-LAST:event_btnIrParaLoginMouseEntered

    private void btnIrParaLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIrParaLoginMouseExited
        toggleBtnImage(evt, "default", "Botão Próximo");
    }//GEN-LAST:event_btnIrParaLoginMouseExited

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        toggleBtnImage(evt, "hover", "Botão Fechar");
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        toggleBtnImage(evt, "default", "Botão Fechar");
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        closeApplication();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnIrParaLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIrParaLoginMouseClicked
        changeView();
    }//GEN-LAST:event_btnIrParaLoginMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnIrParaLogin;
    // End of variables declaration//GEN-END:variables

    private void toggleBtnImage(java.awt.event.MouseEvent e, String action, String image) {
      if("hover".equals(action)) {
          image = "/" + image + " - hover.png";
      } else if("default".equals(action)) {
          image = "/" + image + ".png";
      }
      
      ((JLabel) e.getSource()).setIcon(new ImageIcon(getClass().getResource(image)));
    }

    private void closeApplication() {
      System.exit(0);
    }

    private void changeView() {
      
    }
}
