/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.ImageIcon;

/**
 *
 * @author Lucas Oliveira
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        initProps();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCard = new javax.swing.JPanel();
        primeiroAcesso1 = new views.PrimeiroAcesso(this.pnCard);
        login1 = new views.Login();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Superavit");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        pnCard.setFocusable(false);
        pnCard.setPreferredSize(new java.awt.Dimension(1300, 700));
        pnCard.setLayout(new java.awt.CardLayout());
        pnCard.add(primeiroAcesso1, "card2");
        pnCard.add(login1, "card3");

        getContentPane().add(pnCard);
        pnCard.setBounds(0, 0, 1300, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initProps() {
      this.setIconImage(new ImageIcon(getClass().getResource("/dolar-sign.png")).getImage());
      this.setLocationRelativeTo(null);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private views.Login login1;
    private javax.swing.JPanel pnCard;
    private views.PrimeiroAcesso primeiroAcesso1;
    // End of variables declaration//GEN-END:variables
}
